### ISSUE TITLE
file name for a series of solvent calculations

### ISSUE THREAD

**Issue by NathandB94** [CrystalGrowerOrg/cgaspects#75]
I have done a series of simualtions that uses the solvent name from calculated energies as the name of the folder and XYZ file. This means that the calculations are not running correctly for crystalaspects. This does work for CDA but not for the aspect ratios where the XYZ file is required. I think this can be solved, but I cannot do this myself yet. 

CA:GUI-INFO: Started Calculations...
Traceback (most recent call last):
  File "/Users/Nathan/Documents/GitHub/crystalaspects/src/crystalaspects/analysis/gui_threads.py", line 98, in run
    xyz_df = ar.collect_all(
             ^^^^^^^^^^^^^^^
  File "/Users/Nathan/Documents/GitHub/crystalaspects/src/crystalaspects/analysis/ar_dataframes.py", line 221, in collect_all
    sim_num = re.findall(r"\d+", file.name)[-1]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range

**Comment by AJen01** [comment]
Can you check if this is fixed now?

**Comment by NathandB94** [comment]
For CDA it works, but not for PCA

> Can you check if this is fixed now?
