### ISSUE TITLE
Crystallographic Directional analysis is not working

### ISSUE THREAD

**Issue by NathandB94** [CrystalGrowerOrg/cgaspects#93]
This is from both the download and a previous version. CDA is not working but PCA and growth rates are. The error is found below

Traceback (most recent call last):
  File "/Users/Nathan/Documents/GitHub/crystalaspects/src/cgaspects/analysis/gui_threads.py", line 132, in run
    cda_df = build_cda(
             ^^^^^^^^^^
  File "/Users/Nathan/Documents/GitHub/crystalaspects/src/cgaspects/analysis/ar_dataframes.py", line 77, in build_cda
    [
  File "/Users/Nathan/Documents/GitHub/crystalaspects/src/cgaspects/analysis/ar_dataframes.py", line 78, in <listcomp>
    parse_simulation_parameters_file(f, directions)
  File "/Users/Nathan/Documents/GitHub/crystalaspects/src/cgaspects/analysis/ar_dataframes.py", line 46, in parse_simulation_parameters_file
    for len_line in lines[frame:]:
                          ^^^^^
UnboundLocalError: cannot access local variable 'frame' where it is not associated with a value

**Comment by AJen01** [comment]
Fixed in [462e384](https://github.com/CrystalGrowerOrg/cgaspects/commit/462e384dd43e09de7ad52820160cfb75c7f2c242)
